let
    Source = Excel.Workbook(File.Contents("C:\Users\sarit\OneDrive\POWER BI DATA\EmployeeData.xlsx"), null, true),
    EmployeeData1_Sheet = Source{[Item="EmployeeData1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(EmployeeData1_Sheet, [PromoteAllScalars=true]),
    #"Removed NationalIDNumber, ContactID, LoginID & Manager ID" = Table.RemoveColumns(#"Promoted Headers",{"NationalIDNumber", "ContactID", "LoginID", "ManagerID"}),
    #"Changed Bday data Type" = Table.TransformColumnTypes(#"Removed NationalIDNumber, ContactID, LoginID & Manager ID",{{"BirthDate", type date}}),
    #"Replaced M-Married" = Table.ReplaceValue(#"Changed Bday data Type","M","Married",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Replaced S-Single" = Table.ReplaceValue(#"Replaced M-Married","S","Single",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Added Column By ex for Gender" = Table.AddColumn(#"Replaced S-Single", "Custom", each if [Gender] = "M" then "Male" else if [Gender] = "F" then "Female" else null, type text),
    #"Removed Gender" = Table.RemoveColumns(#"Added Column By ex for Gender",{"Gender"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Gender",{{"Custom", "Gender"}}),
    #"Changed Type of Hire Date" = Table.TransformColumnTypes(#"Renamed Columns",{{"HireDate", type date}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type of Hire Date",{"CurrentFlag", "rowguid"}),
    #"Reordered Gender Column" = Table.ReorderColumns(#"Removed Columns",{"EmployeeID", "Title", "BirthDate", "Gender", "MaritalStatus", "HireDate", "Dept", "Salary", "Job Grade"}),
    #"Merged Dept & Job Grade" = Table.CombineColumns(#"Reordered Gender Column",{"Dept", "Job Grade"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"Dept - Job Grade"),
    #"Duplicated Column" = Table.DuplicateColumn(#"Merged Dept & Job Grade", "Title", "Title - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "Title", "Title - Copy.1"),
    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column1",{{"Title - Copy", "Title - Lower"}}),
    #"Inserted Lowercased Text" = Table.AddColumn(#"Renamed Columns1", "lowercase", each Text.Lower([#"Title - Lower"]), type text),
    #"Uppercased Text" = Table.TransformColumns(#"Inserted Lowercased Text",{{"Title - Copy.1", Text.Upper, type text}}),
    #"Renamed new column" = Table.RenameColumns(#"Uppercased Text",{{"Title - Copy.1", "Upper - Title"}}),
    #"Added Conditional Column" = Table.AddColumn(#"Renamed new column", "Title With Prefix", each if [Gender] = "Male" then "Mr. " else if [MaritalStatus] = "Single" then "Ms. " else if [MaritalStatus] = "Married" then "Mrs. " else null),
    #"Renamed Columns2" = Table.RenameColumns(#"Added Conditional Column",{{"Title With Prefix", "Prefix"}}),
    #"Inserted Title With Prefix" = Table.AddColumn(#"Renamed Columns2", "Title With Prefix", each Text.Combine({[Prefix], [Title]}, " "), type text),
    #"Removed Columns1" = Table.RemoveColumns(#"Inserted Title With Prefix",{"Title", "Prefix"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns1",{"EmployeeID", "Title With Prefix", "BirthDate", "Gender", "MaritalStatus", "HireDate", "Salary", "Dept - Job Grade", "Title - Lower", "Upper - Title", "lowercase"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns",{"Title - Lower"}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Removed Columns2",{{"Upper - Title", Text.Proper, type text}})
in
    #"Capitalized Each Word"
